language: c
compiler:
  # FIXME: Enable clang once we fix the compiler errors
  #- clang
  - gcc
env:
  # FIXME: If we want to check assembly too SYNTAX_ONLY needs to be 0
  # FIXME: We'd like to build with WARNINGS_AS_ERRORS=1 but there are too
  # many warnings firing right now
  - SYNTAX_ONLY=1 WARNINGS_AS_ERRORS=0 VERBOSE=1
# Hint to TravisCI that we want to use their container infrastructure
sudo: false
script:
  - ${CC} -v --version
  - cd c/ && make -j2
