language: c
env:
  global:
    # FIXME: If we want to check assembly too SYNTAX_ONLY needs to be 0
    - SYNTAX_ONLY=1
    # FIXME: We'd like to build with WARNINGS_AS_ERRORS=1 but there are too many warnings firing right now
    - WARNINGS_AS_ERRORS=0
    - VERBOSE=0
    - SUPPRESS_WARNINGS=1
    - REPORT_CC_FILE=2
  matrix:
    # Note: Can't use CC variable as TravisCI will override it
    - C_COMPILER=gcc-5
    - C_COMPILER=clang-3.8
# Hint to TravisCI that we want to use their container infrastructure
sudo: false
git:
  depth: 1
addons:
  apt:
    sources:
      # For newer gcc
      - ubuntu-toolchain-r-test
      # For Clang
      - llvm-toolchain-precise-3.8
    packages:
      # These are needed for compiling with -m32
      # otherwise including system header files might result in
      # errors (e.g. ``fatal error: bits/predefs.h: No such file or directory``)
      - libc6-dev-i386
      - gcc-5
      - clang-3.8
script:
  - ${C_COMPILER} -v --version
  - cd c/ && make -j2 CC=${C_COMPILER}
matrix:
  include:
    env: NAME="Sanity checks"
    script:
      - c/check.py
